[package]
name = "yew-todo"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = "0.19.3"
log = "0.4.6"
wasm-logger = "0.2.0"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.12"                    # or the latest version
gloo-net = "0.4"
serde = { version = "1.0", features = ["derive"] }
